In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
car=pd.read_csv('car_evaluation.csv')

In [3]:
car.head()

vhigh vhigh.1  2 2.1  small   low  unacc
0  vhigh   vhigh  2   2  small   med  unacc
1  vhigh   vhigh  2   2  small  high  unacc
2  vhigh   vhigh  2   2    med   low  unacc
3  vhigh   vhigh  2   2    med   med  unacc
4  vhigh   vhigh  2   2    med  high  unacc

In [4]:
car.shape

(1727, 7)

In [5]:
car1=car.rename({'vhigh':'buing','vhigh.1':'maint','2':'doors','2.1':'person','small':'lug_boot','low':'safety','unacc':'outcome'},axis=1)

In [6]:
car1.head()

buing  maint doors person lug_boot safety outcome
0  vhigh  vhigh     2      2    small    med   unacc
1  vhigh  vhigh     2      2    small   high   unacc
2  vhigh  vhigh     2      2      med    low   unacc
3  vhigh  vhigh     2      2      med    med   unacc
4  vhigh  vhigh     2      2      med   high   unacc

In [7]:
car1.isnull().sum()

buing       0
maint       0
doors       0
person      0
lug_boot    0
safety      0
outcome     0
dtype: int64

In [8]:
for i in car1.columns:
    print(f'Consider Outcome and {i} columns...........')
    print(pd.crosstab(car1['outcome'],car1[i]),'\n')

Consider Outcome and buing columns...........
buing    high  low  med  vhigh
outcome                       
acc       108   89  115     72
good        0   46   23      0
unacc     324  258  268    359
vgood       0   39   26      0 

Consider Outcome and maint columns...........
maint    high  low  med  vhigh
outcome                       
acc       105   92  115     72
good        0   46   23      0
unacc     314  268  268    359
vgood      13   26   26      0 

Consider Outcome and doors columns...........
doors      2    3    4  5more
outcome                      
acc       81   99  102    102
good      15   18   18     18
unacc    325  300  292    292
vgood     10   15   20     20 

Consider Outcome and person columns...........
person     2    4  more
outcome                
acc        0  198   186
good       0   36    33
unacc    575  312   322
vgood      0   30    35 

Consider Outcome and lug_boot columns...........
lug_boot  big  med  small
outcome                  
acc       

In [9]:
# print(car1['buing'].value_counts())
# print(car1.maint.value_counts())
# print(car1.doors.value_counts())
# print(car1.person.value_counts())
# print(car1.lug_boot.value_counts())
# print(car1.safety.value_counts())
# print(car1.outcome.value_counts())

for i in car1.columns:
    print(f'consider column {i}..........')
    print(car1[i].value_counts(),'\n')


consider column buing..........
med      432
high     432
low      432
vhigh    431
Name: buing, dtype: int64 

consider column maint..........
med      432
high     432
low      432
vhigh    431
Name: maint, dtype: int64 

consider column doors..........
3        432
4        432
5more    432
2        431
Name: doors, dtype: int64 

consider column person..........
more    576
4       576
2       575
Name: person, dtype: int64 

consider column lug_boot..........
big      576
med      576
small    575
Name: lug_boot, dtype: int64 

consider column safety..........
med     576
high    576
low     575
Name: safety, dtype: int64 

consider column outcome..........
unacc    1209
acc       384
good       69
vgood      65
Name: outcome, dtype: int64 



In [10]:
for i in range(len(car1.doors)):
    if car1.doors[i]=='5more':
        car1.doors[i]='6'

In [11]:
for i in range(len(car1.person)):
    if car1.person[i]=='more':
        car1.person[i]='10'

In [12]:
car1.doors.value_counts()

6    432
3    432
4    432
2    431
Name: doors, dtype: int64

In [13]:
car1.person.value_counts()

10    576
4     576
2     575
Name: person, dtype: int64

In [14]:
from sklearn.preprocessing import LabelEncoder

In [15]:
la=LabelEncoder()

In [16]:
car1.loc[:,['buing','maint','doors','person','lug_boot','safety','outcome']]=car1.loc[:,['buing','maint','doors','person','lug_boot','safety','outcome']].apply(la.fit_transform)

In [17]:
car1.head()

buing  maint  doors  person  lug_boot  safety  outcome
0      3      3      0       1         2       2        2
1      3      3      0       1         2       0        2
2      3      3      0       1         1       1        2
3      3      3      0       1         1       2        2
4      3      3      0       1         1       0        2

In [18]:
x=car1.drop('outcome',axis=1)
y=car1.outcome

In [19]:
print(x.shape)
print(y.shape)

(1727, 6)
(1727,)


In [20]:
from sklearn.model_selection import train_test_split

In [21]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=40)

In [22]:
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(1208, 6) (519, 6) (1208,) (519,)


In [23]:
from sklearn.neighbors import KNeighborsClassifier

In [24]:
kn=KNeighborsClassifier()

In [25]:
kn.fit(x_train,y_train)

KNeighborsClassifier()

In [26]:
y_pred=kn.predict(x_test)

In [27]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [28]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[ 68   0  42   0]
 [  9   7   2   0]
 [  0   0 375   0]
 [  2   1   4   9]]
              precision    recall  f1-score   support

           0       0.86      0.62      0.72       110
           1       0.88      0.39      0.54        18
           2       0.89      1.00      0.94       375
           3       1.00      0.56      0.72        16

    accuracy                           0.88       519
   macro avg       0.91      0.64      0.73       519
weighted avg       0.88      0.88      0.87       519



In [29]:
print(accuracy_score(y_test,y_pred))

0.884393063583815


In [30]:
# from imblearn.under_sampling import RandomUnderSampler
# from imblearn.over_sampling import SMOTE
from imblearn.over_sampling import RandomOverSampler

In [31]:
# sc=RandomUnderSampler()
# sc=SMOTE()
sc=RandomOverSampler()

In [32]:
x_train_smote,y_train_smote=sc.fit_sample(x_train,y_train)

In [33]:
print(x.shape,y.shape)
print(x_train.shape,y_train.shape)
print(x_train_smote.shape,y_train_smote.shape)

(1727, 6) (1727,)
(1208, 6) (1208,)
(3336, 6) (3336,)


In [34]:
kn.fit(x_train_smote,y_train_smote)

KNeighborsClassifier()

In [35]:
y_predict=kn.predict(x_test)

In [36]:
print(accuracy_score(y_test,y_predict))

0.6319845857418112
